name: Deploy Vue.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install project dependencies
        run: npm install

      - name: Build Vue.js app
        run: npm run build

      - name: Copy files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "dist/"  # Adjust the source path based on your project structure
          target: "/var/www/html"  # Adjust the target path on your EC2 instance

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /var/www/html
            pm2 stop your-app-name  # Adjust the process name based on your setup
            npm install
            pm2 start your-app-name  # Adjust the process name based on your setup
